name: Run hello.py on PR File Change

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - 'hello.py'  # Only trigger when this file is changed

jobs:
  run-python-on-pr:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run hello.py
        run: python hello.py
